### PR TITLE
Use subst as a workaround for long paths in tests

### PR DESCRIPTION
**Pull request by pjk25**
Thanks to @lukebakken for thinking up this solution

### CODE REVIEW

**Comment by pjk25** [comment]
I wonder, is it worth making the letter of the virtual drive configurable? Right now it's just `b`.

**Comment by lukebakken** [comment]
> I wonder, is it worth making the letter of the virtual drive configurable? Right now it's just b.

If we ever see a conflict with `b` we can modify this script to test out a couple letters.

**Comment by acammack** [comment]
`B` was historically the second floppy drive, so for the sorts of systems we expect to run on it should be available and probably avoided by other software for compatibility reasons. IIRC, `subst` can also create non-letter drives like `1`, so that may be an option as well if Erlang can handle paths on drives that aren't letters.

**Review by lukebakken — APPROVED** [review]
Tested locally and this works great!

**Pull request merged**
